---
platform: linux

inputs:
  - name: tkgi-app-tracker-repo

outputs:
  - name: foundation-reports

params:
  FOUNDATIONS: "dc01,dc02,dc03,dc04" # Comma-separated list of foundations
  S3_ENDPOINT:
  S3_ACCESS_KEY_ID:
  S3_SECRET_ACCESS_KEY:
  S3_BUCKET: "reports"
  MAX_AGE_DAYS: "7" # Only retrieve reports newer than this

run:
  path: tkgi-app-tracker-repo/ci/tasks/retrieve-foundation-reports/task.sh
