---
platform: linux

inputs:
- name: tkgi-app-tracker-repo

params:
  MESSAGE: "TKGI App Tracker notification"
  NOTIFICATION_TYPE: "info"
  WEBHOOK_URL:

run:
  path: tkgi-app-tracker-repo/ci/tasks/notify/task.sh
