---
platform: linux

inputs:
  - name: tkgi-app-tracker-repo
  - name: config-repo

outputs:
  - name: collected-data

params:
  CONFIG_REPO: ../../config-repo
  # Foundation Configuration
  FOUNDATION:
  DATACENTER:
  ENVIRONMENT:

  # TKGI/Ops Manager Configuration
  OM_TARGET:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  TKGI_API_ENDPOINT:
  TESTING_MODE: false

run:
  path: tkgi-app-tracker-repo/ci/tasks/collect-data/task.sh
